apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: nuclio
    meta.helm.sh/release-namespace: nuclio
  labels:
    app: nuclio
    app.kubernetes.io/managed-by: Helm
    release: nuclio
  name: nuclioapigateways.nuclio.io
spec:
  conversion:
    strategy: None
  group: nuclio.io
  names:
    kind: NuclioAPIGateway
    listKind: NuclioAPIGatewayList
    plural: nuclioapigateways
    singular: nuclioapigateway
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true