apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-adaptor-role
  namespace: nuclio
rules:
  - apiGroups:
      - "nuclio.io"
    resources:
      - nucliofunctions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-adaptor-rolebinding
  namespace: nuclio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-adaptor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: monitoring